apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-nfs-pv
  namespace: {{ .Values.namespace}}
spec:
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-subdir
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.nfs.server_ip }}
    path: {{ .Values.nfs.path }}
    readOnly: false

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-nfs-pvc
  namespace: {{ .Values.namespace}}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs-subdir"
  resources:
    requests:
      storage: 100Mi