apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-fe
  namespace: {{ .Values.namespace}}
  labels:
    app: {{ .Values.appName }}
    type: frontend
spec:
  containers:
  - name: mpife
    image: {{ .Values.image.name}}:{{ .Values.image.tag }}
    command: [ "/usr/sbin/sshd", "-D" ]
  
    volumeMounts:
      - name: nfs-volume
        subPath: {{ .Values.nfs.subpath}}
        mountPath: "/nfs"
      - name: config-volume
        mountPath: "/config"
  volumes:
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: {{ .Release.Name }}-nfs-pvc
    - name: config-volume
      configMap:
        name: {{ .Release.Name }}-configmap
        items:
          - key: hostfile
            path: hostfile